name: Deploy to GitHub Pages (with PAT)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Type check
      run: npm run type-check
      
    - name: Build
      run: npm run build
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        # Use Personal Access Token if GITHUB_TOKEN doesn't work
        github_token: ${{ secrets.PAT_TOKEN }}
        publish_dir: ./dist
        cname: oh.moonwave.kr
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        
    - name: Deploy Status
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "🌐 Site URL: https://oh.moonwave.kr"
        echo "📅 Deployed at: $(date)"